### ISSUE TITLE
Using npm version with node is brokened

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-javascript-client#11]
```
/Users/roger/Projects/zooniverse/pjctest/node_modules/panoptes-client/lib/utils.js:7
if (!exists(window) && !exists(window.console)) {
            ^
ReferenceError: window is not defined
```

This has all been commented out on GitHub (https://github.com/zooniverse/panoptes-javascript-client/blob/master/lib/utils.js), but we should probably release a new version

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/panoptes-javascript-client/commit/68260a777788419887362fd16f46c68a0c77e604
