### ISSUE TITLE
Remove `test-mac` once testling gets a fix?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-javascript-client#3]
I wasn't sure why there were separate `test` and `test-mac` commands, but I've just found https://github.com/substack/testling/issues/108. We should probably remove the command and add PhantomJS as a `devDependency` once it's fixed.

**Comment by brian-c** [comment]
`test-mac` runs tests in Chrome, which is nice for interactive debugging and figuring out some occasional weird behavior in Phantom.

`test` should work with Phantom automatically, if it's installed.
