### ISSUE TITLE
Suggestion: Document how to choose staging or production

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/panoptes-javascript-client#47]
I heard that it's the NODE_ENV variable and confirmed that in the code (https://github.com/zooniverse/panoptes-javascript-client/blob/0713172c27c0f6a22333a2ed97eb39865b8eb05e/lib/config.js#L56) but it doesn't seem to be mentioned in https://zooniverse.github.io/panoptes-javascript-client/

Might PR this myself later but just noting it for now.

**Comment by rogerhutchings** [comment]
fixed via 207bc78e8669821146e488fcfb644fa8f0c9be57
