### ISSUE TITLE
"Got new bearer token" no longer logs distinct tokens

### ISSUE THREAD

**Issue by marten** [zooniverse/panoptes-javascript-client#54]
https://github.com/zooniverse/panoptes-javascript-client/blob/e7115da90a84089e115b571bb70956d35a0df351/lib/oauth.js#L232

The start of all bearer tokens is going to be the same for all. Better slice from the end.

**Comment by rogerhutchings** [comment]
`String.slice()` does slice from the end with a negative index - [link](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/slice#Using_slice()_with_negative_indexes)
