### ISSUE TITLE
Calling save() on fetched incomplete classification results in GET, not PUT

### ISSUE THREAD

**Issue by itsravenous** [zooniverse/panoptes-javascript-client#56]
```js
api.type('classifications/incomplete')
  .get()
  .then(classifications => {
    classifications[0].save(); // GET https://panoptes-staging.zooniverse.org/api/classifications/77449
  });
```

Re-saving complete classifications results in a PUT as expected (though obviously the API rejects the save), as does resaving other types, e.g. subjects.

I'm experiencing this on OW but I'll put together a test case to rule out project-specific weirdness.

**Comment by itsravenous** [comment]
Confirmed in an [isolated test case](https://gist.github.com/itsravenous/0b094bff34c420136966257fa06a4d64)

**Comment by itsravenous** [comment]
Problem seems to be that `Resource#save()` calls `Resource#refresh()` before doing the PUT. Not sure why the refresh GET gives a 404 though - the docs indicate that [single classifications can be retrieved providing they are incomplete].

**Comment by saschaishikawa** [comment]
Confirmed: When fetching an incomplete classification, doing a `classification.update({completed: true}).save()` results in a GET request instead of PUT. Can someone have a look to see if there's a quick fix for the back end? @camallen @marten

**Comment by camallen** [comment]
I think this is just a case of the docs being out of sync, see the incomplete section http://docs.panoptes.apiary.io/#reference/classification/classification-collection/list-all-classifications you should be able to filter using subject_id and even the classification id there [ala here](https://github.com/RestPack/restpack_serializer#by-primary-key).

Not the GET is for the etag for the updated resource before doing the subsequent PUT with the up to date version of the resource.

**Comment by itsravenous** [comment]
OK, gotcha, so I guess this client needs to make an exception for classifications when doing the fetch for etag.

I don't get why fetching incomplete classifications as single items (e.g. `/classifications/1`) is explicitly disabled though - since you can fetch them by searching the collection route for the id it's not a "permission" thing, and we need to fetch the resource to get the etag anyway. If we could access the classification by id (as you can with e.g. subjects, projects, workflows) the client wouldn't need to make an exception.

If anything, the "old" behaviour makes more sense to me - making classifications immutable once "finished", but I may be missing something.

**Comment by camallen** [comment]
Basically unsaved classifications aren't full classifications yet and we ended up with really complex rules and URL params to access the different scopes and it was horrible. So i just broke it up to specific collection routes which added the default scopes, see https://github.com/zooniverse/Panoptes/pull/1732 for details.

All that said we can add this back in to the fetch by id (show) route since you know the resource exists by splitting the show index route [here](https://github.com/zooniverse/Panoptes/blob/2f454e36e711fe9e8ec641cde6fd01b08a9e0d2d/app/models/classification.rb#L31) to remove the scope for only complete classifications. Fancy filing an issue about this on panoptes repo?

**Comment by camallen** [comment]
also re 
> If anything, the "old" behaviour makes more sense to me - making classifications immutable once "finished", but I may be missing something.

Classifications are immutable once they are complete, [see](https://github.com/zooniverse/Panoptes/blob/2f454e36e711fe9e8ec641cde6fd01b08a9e0d2d/app/models/classification.rb#L32).

**Comment by itsravenous** [comment]
Cool, thanks for the deets! Re immutability, sorry: that was _terrible_ phrasing on my part. I meant that it implied immutability of complete classifications (because you wouldn't be able to fetch them to get an ETag).

**Comment by camallen** [comment]
yeah - however other use cases required complete classifications and this is a user's contributed data so they should have access to it.
