### ISSUE TITLE
Ability to copy a Federated Projects 'template project' workflows via the client

### ISSUE THREAD

**Issue by trouille** [zooniverse/panoptes-javascript-client#57]
This is part of the Notes from Nature Year 2 effort, see https://github.com/zooniverse/Panoptes-Front-End/issues/2968

This particular request is so that BioSpex, the content management system about half of Notes from Nature researchers use, will be used as a portal through which to create subject sets, pick a template workflow, etc. in order to add a new project to Notes from Nature federated project. See 'Plans to Support Biospex' at https://docs.google.com/document/d/1_9yhO_i7wQf_eph70H5pucD9EeUHXtBCSnI5WbDKnYU/edit

**Comment by srallen** [comment]
I don't think this is a js client issue. If an endpoint needs work for this, then it should be an issue on the Panoptes repository.
