### ISSUE TITLE
Figure out why this isn't working in Node

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-javascript-client#8]
I just tried accessing a resource in a subject upload script I'm writing in Node, and the client silently exits. I don't suppose you've tried anything like this @chrissnyder / @brian-c ?

**Comment by chrissnyder** [comment]
Any indication of what's happening? Haven't run into this myself.

**Comment by brian-c** [comment]
Are you loading a global Promise and XMLHttpRequest polyfill?

See https://github.com/zooniverse/panoptes-subject-uploader/blob/master/lib/polyfills.coffee

**Comment by rogerhutchings** [comment]
@chrissnyder no, but @camallen reported a similar problem.

@brian-c No - I've just tried adding them though, and now I'm getting a result, thanks. Shouldn't these be loaded by the client?

**Comment by brian-c** [comment]
The client expects to be run in a browser. The next version can be smarter.

**Comment by rogerhutchings** [comment]
Okay, I'll create a new issue for that.

**Comment by rogerhutchings** [comment]
Spoke too soon. Requesting resources works as expected, attempting to save them back to the API doesn't.

**Comment by chrissnyder** [comment]
Couple things happening here.

First, to create new resources, you need to login first. Logging in from the client was broken because it got out of sync from Panoptes. I've submitted a PR to fix this.

Second, you'll need to make sure to load a XMLHttpRequest polyfill that is cookie-aware, such as https://www.npmjs.com/package/xmlhttprequest-cookie, otherwise every authenticated request (basically any POSTs or PUTs will fail with a 422 error).

**Comment by rogerhutchings** [comment]
Cool, I've merged that PR. But I'm pretty sure neither of these is the cause of the problem, as it would be returning _something_ if they were, even if only a 'Not Authenticated' error.

I've created a repo to demonstrate this: https://github.com/rogerhutchings/pjctest. There are two weirdnesses:

- After logging in, it just runs forever
- The silent failure problem when creating resources

If I'm obviously doing something wrong, let me know!

**Comment by chrissnyder** [comment]
Adding a bit of logging:

```
        var newProject = _client.api.type('projects').create({
            'name': 'Second Upload Test',
            'description': 'A project for testing uploads',
            'primary_language': 'en-us',
            'private': true,
        });
        return newProject.save()
            .then(function(project) {
                console.log(project);
                process.exit(0);
            })
            .catch(function(error) {
                console.log(error);
                process.exit(1);
            });
```

Produces the following error: `[Error: {"schema"=>"contains additional properties [\"name\"] outside of the schema when none are allowed"}]` Chaging `name` to `display_name` fixes this and creates the resource as expected.

**Comment by rogerhutchings** [comment]
Oh, cool - can someone (I don't mind doing it) update the docs at http://docs.panoptes.apiary.io/#reference/projects/project-collection/create-a-project ?
