### ISSUE TITLE
Load Promise, XMLHttpRequest polyfills if needed

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-javascript-client#9]
Originally via #8.

Currently, if either the Promise or XMLHttpRequest polyfills are missing, the client will silently exit. It should include both of these as dependencies and conditionally load them if needed.

**Comment by brian-c** [comment]
Node 0.12 has native promises, so I wouldn't really worry about those.

I'd switch from using raw XMLHttpRequest to using the superagent lib, which loads code to use the right interface automatically.

**Comment by srallen** [comment]
client lib is using superagent.
